# YOLO格式的VisDrone数据集配置
path: E:\Project\VisDrone_Experiment\VisDrone2019-DET  # 数据集根目录

# 图像和标注路径
train: images/train
val: images/val
test: images/test_dev

# 标注目录（转换后的YOLO格式）
train_labels: labels/train
val_labels: labels/val
test_labels: labels/test_dev

# 类别数量
nc: 10

# 类别名称
names: ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor']

# 训练参数
img_size: 640
batch_size: 16
epochs: 80
